"""create interview_turns table

Revision ID: 02b0ff496c96
Revises: 
Create Date: 2026-07-17 07:56:17.218912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b0ff496c96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_role', sa.String(), nullable=True),
    sa.Column('user_transcription', sa.Text(), nullable=False),
    sa.Column('ai_feedback', sa.Text(), nullable=False),
    sa.Column('ai_next_question', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_turns_id'), 'interview_turns', ['id'], unique=False)
    op.create_index(op.f('ix_interview_turns_job_role'), 'interview_turns', ['job_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_turns_job_role'), table_name='interview_turns')
    op.drop_index(op.f('ix_interview_turns_id'), table_name='interview_turns')
    op.drop_table('interview_turns')
    # ### end Alembic commands ###
